name: CI/CD for SpringBoot application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: ap-northeast-1

jobs:
    - name: Login to Amazon ECR

      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-region: ${{ env.AWS_REGION }}

    - name: Build and push Docker image to Amazon ECR
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/spring-app:$(date +'%Y%m%d%H%M%S')
